ubuntu/ubuntu-project-docs

- docs/.custom_wordlist.txt
- docs/reference/governance/code-of-conduct.md
- docs/reference/governance/index.md
Adds the Ubuntu Code of Conduct. This is commit copies the text from https://ubuntu.com/community/ethos/code-of-conduct at the time of commit b239d46151ccaac73077bb8cacd1fc683914f876.
> Add Ubuntu Code of Conduct

- docs/.custom_wordlist.txt
- docs/reference/governance/code-of-conduct.md
- docs/reference/governance/diversity-policy.md
Adds the Ubuntu diversity policy. This is commit copies the text from https://ubuntu.com/community/ethos/diversity at the time of commit 7005091adbeb5951d2ddd3b8b4253810aa05b3bc.
> Add Ubuntu Diversity Policy

- docs/reference/governance/index.md
- docs/reference/governance/mission.md
Adds the Ubuntu Mission statement. This commit copies the text from https://ubuntu.com/community/ethos/mission at the time of commit 6b825599fc8a7f60f4662be6280167b4be74790a.
> Add Ubuntu mission statement

- .readthedocs.yaml
Due to broken links that may need to be followed up on before we can redirect correctly, we may not want to have the docs fail to build on warnings. Broken links are going to be very frequent, especially at the start.
> Disable "fail on warning"

- docs/conf.py
The https://www.gnu.org/philosophy/free-sw.html link is causing the linkchecker in our automated tests to "hang" for no reason. Since the link works when clicked on, I'm adding it to the list of URLs ignored by the linkchecker.
> Fix hanging linkchecker

- .readthedocs.yaml
- docs/.sphinx/spellingcheck.yaml
- docs/conf.py
- docs/reference/glossary.md
- docs/requirements.txt
This PR adds a functionality from the Packaging Guide, which allows use of the `{manpage}` or `:manpage:` role (in markdown or rST respectively).
It means we don't need to keep updating manpage links every time there's a new update.
Using the manpage role autopopulates the link to the relevant manpage on the version of Ubuntu the reader is using.
Usage example:
```
{manpage}`autopkgtest(1)`
:manpage:`autopkgtest(1)`
```
Renders the link to the manpage automatically as:
`https://manpages.ubuntu.com/manpages/plucky/en/man1/autopkgtest.1.html`
Thanks to @dviererbe for the [initial implementation](https://github.com/canonical/ubuntu-packaging-guide/commit/89df9a6bc8572099043f39074c9db663a7db1aaf) that formed the basis of this PR.
This PR fixes: #24
> Add manpage role for autolinking to manpages

- docs/.custom_wordlist.txt
- docs/conf.py
- docs/reference/glossary.md
- docs/requirements.txt
In this PR I add the hoverxref functionality\*.
I also compacted the glossary by combining the terms with their acronyms instead of having acronyms point to terms elsewhere. This has some advantages:
1) You can refer to terms either by the full name or the acronym and be served the same description for either/both
2) The glossary becomes easier to manage (with no duplication)
3) Hover-overs should serve the same content in the tooltip
\* We will eventually want to deprecate this in favour of the inbuilt RTD functionality, but only once they have provided customisation capability (to be filed as a followup issue)
> Tidy up glossary

- docs/staging/mirror-scripts.md
- docs/staging/mirrors.md
- docs/staging/push-mirroring.md
In the process of migrating the "package archive" wiki page, I discovered a few related pages on mirroring that also need to be moved.
These pages have been converted to markdown and links have been updated.
> Add mirroring pages

- docs/staging/new-packages.md
- docs/staging/package-archive.md
- docs/staging/sponsorship-process.md
Add the Package Archive content from the wiki, including two incidental pages
([sponsorship process](https://wiki.ubuntu.com/UbuntuDevelopment/PackageArchive) and [new packages](https://wiki.ubuntu.com/UbuntuDevelopment/NewPackages))
Converted to markdown, some links have been updated (where possible)
> Add package archive and related pages

- docs/conf.py
- docs/how-to/contribute-docs.md
- docs/requirements.txt
* Change 'manpage' role config to manual
* rationale: the use of a locally sourced (`/usr/lib/...`) Python function for automatically determining the current stable release of Ubuntu is brittle -- it only works on Ubuntu; anyone building the docs on any other system, including a different distro, would run into problems; that wouldn't be user-friendy.
* Add the 'pkg' role for semantic markup of packages
* Add the `sphinx-prompt` extension to enable the `prompt` directive
* Redefine the 'command' role to render like 'literal'
> Improve some Sphinx config

- docs/staging/germinate.md
- docs/staging/package-archive.md
- docs/staging/push-mirroring.md
This changes:
* 'master' to 'main' -- that's in reference to the Ubuntu archive, so even though it might not be called that, I expect it should be self-explanatory and not a problematic change (even if only in the docs for the time being).
* 'blacklist' to 'blocklist' -- in `germinate` terminology. This is more complicated because [`germinate`](https://launchpad.net/germinate), the tool itself, is full of the word. So, to get things moving, I submitted a bug against the tool ([Bug #2114677](https://bugs.launchpad.net/ubuntu/+source/germinate/+bug/2114677)), as well as a first naive attempt at fixing it in the tool ([MP #487117](https://code.launchpad.net/~rkratky/germinate/+git/germinate/+merge/487117)). Let's see how that goes...
> Fix non-inclusive terms

- docs/contributors/bug-fix/bug-control.md
Since I got some questions from my team member asking why
they cannot modify a certain control fields for a Bug (affected Ubuntu serie).
I think it would be useful if we talk briefly about the Ubuntu bug control team.
> Add bug control section in bug fix

- docs/conf.py
Setting configuration for the copybutton extension. This setting allows us to show the terminal prompt in the docs, but when the user clicks the copybutton to copy the command the prompt is stripped.
> Strip prompts from copied code blocks

- docs/maintainers/AA/aa-archive-related-services.md
The drive behind this was to document the disabling procedure.
> AA: add some short doc about autosync

- docs/contributors/bug-fix/package-building.md
The target no longer exists - pointed to relevant manpage instead
> Fix linkcheck error

- docs/.custom_wordlist.txt
- docs/conf.py
- docs/contributors/advanced/resolve-a-migration-issue.md
- docs/contributors/advanced/review-a-merge-proposal.md
- docs/contributors/advanced/sponsor-an-upload.md
- docs/contributors/bug-fix/fix-a-bug-in-a-package.md
- docs/contributors/bug-fix/package-tests.md
- docs/contributors/index-advanced.md
- docs/contributors/index-bug-fix.md
- docs/contributors/index.md
- docs/contributors/new-package/upload-packages-to-ppa.rst
- docs/how-ubuntu-is-made/concepts/glossary.md
- docs/how-ubuntu-is-made/index-processes.md
- docs/how-ubuntu-is-made/processes/automatic-package-testing-autopkgtest.rst
- docs/how-ubuntu-is-made/processes/backports.rst
- docs/how-ubuntu-is-made/processes/merges-and-syncs.rst
- docs/how-ubuntu-is-made/processes/proposed-migration.md
- docs/how-ubuntu-is-made/processes/proposed-migration/autopkgtest-regressions.md
- docs/how-ubuntu-is-made/processes/proposed-migration/failure-to-build-from-source-ftbfs.md
- docs/how-ubuntu-is-made/processes/proposed-migration/index.md
- docs/how-ubuntu-is-made/processes/proposed-migration/issues-preventing-migration.md
- docs/how-ubuntu-is-made/processes/proposed-migration/special-migration-cases.md
- docs/how-ubuntu-is-made/processes/transitions.md
- docs/requirements.txt
- docs/reuse/links.txt
- docs/who-makes-ubuntu/joining/membership-in-core-dev.md
- docs/who-makes-ubuntu/joining/membership-in-packageset.md
* Lotsa edits, markup, formatting, language
* Split into 'process' and 'howto' articles
* Process article chunked into an 'article' series
* Introduced series navig in all parts
* 'Process' and 'Advanced tasks' landing pages updated
* Added deps: articles (to-be-edited) on:
- autopkgtests
- backports (process expl.)
* Misc. edits/renames/additions in other parts
@s-makin, please, have a look at the 'article series' navig. The rest (much editing and fixes still left to do) to follow.
> Proposed migration; first take

- docs/contributors/index-advanced.md
> Remove 'How to' from navig for consistency

- docs/.custom_wordlist.txt
- docs/MIR/main-inclusion-review.md
> MIR: explain when a MIR is needed

- docs/contributors/index.md
The "testing" section was replaced by "QA and testing", so this toctree points to a non-existing page which results in errors in local builds
> Remove empty section

- docs/how-ubuntu-is-made/concepts/glossary.md
- docs/how-ubuntu-is-made/concepts/package-archive.rst
- docs/how-ubuntu-is-made/processes/proposed-migration/index.md
- docs/release-team/freezes.md
- docs/release-team/release-cycle.md
- docs/release-team/ubuntu-releases.md
Updated the `ubuntu-releases.md` and `freezes.md` pages following Release Team review with @utkarsh2102.
Following this, we will be able to begin redirecting most of the corresponding wiki pages.
During this work, noticed an opportunity for consolidation in the glossary, and updated some headers/anchors for brevity.
---
> Release Team doc review

- docs/who-makes-ubuntu/joining/path-to-upload-rights.md
The diagram on the `path-to-upload-rights.md` page was not rendering correctly and many of the labels had disappeared. After trying and failing several methods to fix the rendering, I decided to break up the diagram - which has the advantage that we can now link to the relevant parts of the diagram from other pages.
---
---
I *think* the changes I've made still reflect the [spirit of the original](https://github.com/canonical/ubuntu-maintainers-handbook/blob/main/Reference/PathToUploadRights.md) - please let me know if that's not the case
> Fix "path to upload rights" diagram

- docs/release-team/mirrors.md
As title - toc is showing at the top of the page
> Hide toc from page
